version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    command: mongod --auth
    environment:
        MONGO_INITDB_DATABASE: fastapi
        MONGO_INITDB_ROOT_USERNAME: admin
        MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - store:/data/db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27018:27017"
    restart: always

  service:
    build: .
    container_name: "FastAPI"
    ports:
      - "8000:8000"
    volumes:
        - type: bind
          source: .
          target: /app
    command: "uvicorn main:app --reload --host 0.0.0.0 --port 8000"
    depends_on:
      - mongodb

volumes:
  store:
