version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: "mongodb"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - store:/data/db
    ports:
      - "27018:27017"
    restart: always

volumes:
  store:
    external: true